### ISSUE TITLE
Polyfill rest parameters 

### ISSUE THREAD

**Issue by AlexBeauchemin** [bojand/promisify-call#2]
Code fails here https://github.com/bojand/promisify-call/blob/master/index.js#L13
For anything using nodejs <6 without harmony flag
Good example of that is using aws lambda, many libraries fails because the rest parameter is not supported (lambda use node 4.3 without harmony flag)

**Comment by AlexBeauchemin** [comment]
https://github.com/bojand/promisify-call/pull/3

**Comment by bojand** [comment]
Fixed with #3. Published as `2.0.4`. Thank you for the PR.
